import type { Collection, Item } from "./types";

export const collections: Collection[] = [
	{
		id: "voyages",
		name: "Voyage Event Reporting",
		icon: "Anchor",
		fields: [
			{ id: "title", label: "Title", type: "text", required: true },
			{ id: "eventKey", label: "Event Key", type: "text", required: false },
			{
				id: "event",
				label: "Event",
				type: "select",
				required: true,
				options: [
					{ value: "arrival", label: "Arrival", color: "#A855F7" },
					{ value: "departure", label: "Departure", color: "#F59E0B" },
					{ value: "bunkering", label: "Bunkering", color: "#10B981" },
				],
			},
			{ id: "eventTime", label: "Event Time", type: "date", required: true },
			{
				id: "voyageNumber",
				label: "Voyage Number",
				type: "text",
				required: false,
			},
			{ id: "fromPort", label: "From Port", type: "text", required: false },
			{ id: "toPort", label: "To Port", type: "text", required: false },
			{ id: "latitude", label: "Latitude", type: "text", required: false },
			{ id: "longitude", label: "Longitude", type: "text", required: false },
			{ id: "windspeed", label: "Wind Speed", type: "text", required: false },
			{
				id: "sailedDistance",
				label: "Sailed Distance",
				type: "text",
				required: false,
			},
			{
				id: "propulsionEnginesHfo",
				label: "Propulsion HFO",
				type: "text",
				required: false,
			},
			{
				id: "propulsionEnginesMgo",
				label: "Propulsion MGO",
				type: "text",
				required: false,
			},
			{
				id: "generatorEnginesHfo",
				label: "Generator HFO",
				type: "text",
				required: false,
			},
			{
				id: "reportedByPosition",
				label: "Reported By Position",
				type: "text",
				required: false,
			},
			{
				id: "reportedByUser",
				label: "Reported By User",
				type: "select",
				required: false,
				options: [
					{ value: "bb1a8097", label: "Jarle Auby", color: "#6366F1" },
					{
						value: "c35ed75a",
						label: "Anders Bjørkestøl Olsen",
						color: "#8B5CF6",
					},
					{
						value: "85be9db9",
						label: "Kaptein Color Hybrid",
						color: "#EC4899",
					},
				],
			},
			{
				id: "status",
				label: "Status",
				type: "select",
				required: false,
				options: [
					{ value: "notSubmitted", label: "Not Submitted", color: "#EF4444" },
					{ value: "submitted", label: "Submitted", color: "#10B981" },
					{ value: "resubmit", label: "Resubmit", color: "#8B5CF6" },
				],
			},
			{ id: "passengers", label: "Passengers", type: "text", required: false },
			{
				id: "cargoMassMetircTones",
				label: "Cargo Mass MT",
				type: "text",
				required: false,
			},
			{ id: "totalHFO", label: "Total HFO", type: "text", required: false },
			{ id: "totalMGO", label: "Total MGO", type: "text", required: false },
		],
	},
	
	{
		id: "employees",
		name: "Employee Directory",
		icon: "Users",
		fields: [
			{ id: "name", label: "Full Name", type: "text", required: true },
			{ id: "email", label: "Email", type: "text", required: true },
			{
				id: "department",
				label: "Department",
				type: "select",
				required: true,
				options: [
					{ value: "engineering", label: "Engineering", color: "#3B82F6" },
					{ value: "operations", label: "Operations", color: "#8FB63E" },
					{ value: "sales", label: "Sales", color: "#10B981" },
				],
			},
			{ id: "hireDate", label: "Hire Date", type: "date", required: false },
		],
	},
	
	{
		id: "inventory",
		name: "Inventory Items",
		icon: "Package",
		fields: [
			{ id: "itemName", label: "Item Name", type: "text", required: true },
			{ id: "quantity", label: "Quantity", type: "text", required: true },
			{
				id: "status",
				label: "Status",
				type: "select",
				required: true,
				options: [
					{ value: "in-stock", label: "In Stock", color: "#10B981" },
					{ value: "low", label: "Low Stock", color: "#F59E0B" },
					{ value: "out", label: "Out of Stock", color: "#EF4444" },
				],
			},
		],
	},
];

export const sampleData: Record<string, Item[]> = {
	voyages: [
		{
			id: "1",
			title: "Color Magic - Report #1001",
			eventKey: "EVT-1001",
			event: "departure",
			eventTime: "2026-02-11T09:00",
			voyageNumber: "VOY-1001",
			fromPort: "Hirtshals",
			toPort: "Larvik",
			latitude: "57.9",
			longitude: "8.7",
			windspeed: "12",
			sailedDistance: "110",
			propulsionEnginesHfo: "2.4",
			propulsionEnginesMgo: "0.8",
			generatorEnginesHfo: "1.2",
			reportedByPosition: "Captain",
			reportedByUser: "bb1a8097",
			status: "submitted",
			passengers: "312",
			cargoMassMetircTones: "850",
			totalHFO: "3.6",
			totalMGO: "0.8",
		},
		{
			id: "2",
			title: "Color Hybrid - Report #1002",
			eventKey: "EVT-1002",
			event: "bunkering",
			eventTime: "2026-02-12T10:00",
			voyageNumber: "VOY-1002",
			fromPort: "Hirtshals",
			toPort: "Kiel",
			latitude: "56.1",
			longitude: "10.2",
			windspeed: "8",
			sailedDistance: "220",
			propulsionEnginesHfo: "3.1",
			propulsionEnginesMgo: "1.2",
			generatorEnginesHfo: "1.5",
			reportedByPosition: "First Officer",
			reportedByUser: "c35ed75a",
			status: "notSubmitted",
			passengers: "280",
			cargoMassMetircTones: "920",
			totalHFO: "4.6",
			totalMGO: "1.2",
		},
		{
			id: "3",
			title: "SuperSpeed 1 - Report #1003",
			eventKey: "EVT-1003",
			event: "arrival",
			eventTime: "2026-02-13T11:00",
			voyageNumber: "VOY-1003",
			fromPort: "Larvik",
			toPort: "Kristiansand",
			latitude: "58.1",
			longitude: "7.9",
			windspeed: "15",
			sailedDistance: "95",
			propulsionEnginesHfo: "1.8",
			propulsionEnginesMgo: "0.6",
			generatorEnginesHfo: "0.9",
			reportedByPosition: "Captain",
			reportedByUser: "85be9db9",
			status: "resubmit",
			passengers: "195",
			cargoMassMetircTones: "430",
			totalHFO: "2.7",
			totalMGO: "0.6",
		},
		{
			id: "4",
			title: "SuperSpeed 2 - Report #1004",
			eventKey: "EVT-1004",
			event: "departure",
			eventTime: "2026-02-14T12:00",
			voyageNumber: "VOY-1004",
			fromPort: "Kristiansand",
			toPort: "Larvik",
			latitude: "58.1",
			longitude: "8.0",
			windspeed: "10",
			sailedDistance: "95",
			propulsionEnginesHfo: "1.9",
			propulsionEnginesMgo: "0.7",
			generatorEnginesHfo: "1.0",
			reportedByPosition: "Captain",
			reportedByUser: "bb1a8097",
			status: "submitted",
			passengers: "210",
			cargoMassMetircTones: "510",
			totalHFO: "2.9",
			totalMGO: "0.7",
		},
		{
			id: "5",
			title: "Color Fantasy - Report #1005",
			eventKey: "EVT-1005",
			event: "bunkering",
			eventTime: "2026-02-15T13:00",
			voyageNumber: "VOY-1005",
			fromPort: "Sandefjord",
			toPort: "Stromstad",
			latitude: "59.1",
			longitude: "10.5",
			windspeed: "6",
			sailedDistance: "75",
			propulsionEnginesHfo: "1.5",
			propulsionEnginesMgo: "0.5",
			generatorEnginesHfo: "0.8",
			reportedByPosition: "Chief Officer",
			reportedByUser: "c35ed75a",
			status: "submitted",
			passengers: "420",
			cargoMassMetircTones: "1100",
			totalHFO: "2.3",
			totalMGO: "0.5",
		},
		{
			id: "6",
			title: "Color Magic - Report #1006",
			eventKey: "EVT-1006",
			event: "arrival",
			eventTime: "2026-02-16T14:00",
			voyageNumber: "VOY-1006",
			fromPort: "Stromstad",
			toPort: "Sandefjord",
			latitude: "59.0",
			longitude: "10.4",
			windspeed: "9",
			sailedDistance: "75",
			propulsionEnginesHfo: "1.6",
			propulsionEnginesMgo: "0.5",
			generatorEnginesHfo: "0.8",
			reportedByPosition: "Captain",
			reportedByUser: "bb1a8097",
			status: "notSubmitted",
			passengers: "398",
			cargoMassMetircTones: "980",
			totalHFO: "2.4",
			totalMGO: "0.5",
		},
		{
			id: "7",
			title: "Color Hybrid - Report #1007",
			eventKey: "EVT-1007",
			event: "departure",
			eventTime: "2026-02-17T15:00",
			voyageNumber: "VOY-1007",
			fromPort: "Kiel",
			toPort: "Oslo",
			latitude: "55.7",
			longitude: "10.9",
			windspeed: "18",
			sailedDistance: "480",
			propulsionEnginesHfo: "5.2",
			propulsionEnginesMgo: "1.8",
			generatorEnginesHfo: "2.1",
			reportedByPosition: "Captain",
			reportedByUser: "85be9db9",
			status: "submitted",
			passengers: "560",
			cargoMassMetircTones: "1450",
			totalHFO: "7.3",
			totalMGO: "1.8",
		},
		{
			id: "8",
			title: "SuperSpeed 1 - Report #1008",
			eventKey: "EVT-1008",
			event: "bunkering",
			eventTime: "2026-02-18T16:00",
			voyageNumber: "VOY-1008",
			fromPort: "Oslo",
			toPort: "Kiel",
			latitude: "59.9",
			longitude: "10.7",
			windspeed: "11",
			sailedDistance: "480",
			propulsionEnginesHfo: "5.0",
			propulsionEnginesMgo: "1.7",
			generatorEnginesHfo: "2.0",
			reportedByPosition: "First Officer",
			reportedByUser: "c35ed75a",
			status: "resubmit",
			passengers: "490",
			cargoMassMetircTones: "1380",
			totalHFO: "7.0",
			totalMGO: "1.7",
		},
	],
	
	employees: [
		{
			id: "1",
			name: "John Smith",
			email: "john.smith@maranics.com",
			department: "engineering",
			hireDate: "2024-01-15",
		},
		{
			id: "2",
			name: "Sarah Connor",
			email: "sarah.connor@maranics.com",
			department: "operations",
			hireDate: "2023-06-20",
		},
		{
			id: "3",
			name: "Mike Johnson",
			email: "mike.johnson@maranics.com",
			department: "sales",
			hireDate: "2025-03-10",
		},
		{
			id: "4",
			name: "Anna Berg",
			email: "anna.berg@maranics.com",
			department: "engineering",
			hireDate: "2022-09-01",
		},
		{
			id: "5",
			name: "Lars Eriksen",
			email: "lars.eriksen@maranics.com",
			department: "operations",
			hireDate: "2023-11-15",
		},
		{
			id: "6",
			name: "Emma Nielsen",
			email: "emma.nielsen@maranics.com",
			department: "sales",
			hireDate: "2024-05-22",
		},
	],
	
	inventory: [
		{ id: "1", itemName: "Hydraulic Pump", quantity: "45", status: "in-stock" },
		{ id: "2", itemName: "Safety Valve", quantity: "8", status: "low" },
		{ id: "3", itemName: "Engine Filter", quantity: "0", status: "out" },
		{ id: "4", itemName: "Fuel Injector", quantity: "22", status: "in-stock" },
		{ id: "5", itemName: "Cooling Fan", quantity: "5", status: "low" },
		{ id: "6", itemName: "Pressure Gauge", quantity: "0", status: "out" },
	],
};