import type { Collection, Item } from "./types";

export const collections: Collection[] = [
	{
		id: "voyages",
		name: "Voyage Event Reporting",
		icon: "Anchor",
		fields: [
			// GENERAL
			{
				id: "title",
				label: "Title",
				type: "text",
				required: true,
				group: "General",
			},
			{
				id: "eventKey",
				label: "Event Key",
				type: "text",
				required: false,
				group: "General",
			},
			{
				id: "event",
				label: "Event",
				type: "select",
				required: true,
				group: "General",
				showInCard: true,
				filterable: true,
				options: [
					{ value: "arrival", label: "Arrival", color: "#A855F7" },
					{ value: "departure", label: "Departure", color: "#F59E0B" },
					{ value: "bunkering", label: "Bunkering", color: "#10B981" },
				],
			},
			{
				id: "eventTime",
				label: "Event Time",
				type: "date",
				required: true,
				group: "General",
			},
			{
				id: "voyageNumber",
				label: "Voyage Number",
				type: "text",
				required: false,
				group: "General",
			},
			
			// ROUTE
			{
				id: "fromPort",
				label: "From Port",
				type: "text",
				required: false,
				group: "Route",
				routeFrom: true,

			},
			{
				id: "toPort",
				label: "To Port",
				type: "text",
				required: false,
				group: "Route",
				routeTo: true,
			},
			{
				id: "latitude",
				label: "Latitude",
				type: "text",
				required: false,
				group: "Route",
			},
			{
				id: "longitude",
				label: "Longitude",
				type: "text",
				required: false,
				group: "Route",
			},
			{
				id: "sailedDistance",
				label: "Sailed Distance",
				type: "text",
				required: false,
				group: "Route",
			},
			{
				id: "windspeed",
				label: "Wind Speed",
				type: "text",
				required: false,
				group: "Route",
			},
			
			// ENGINE & FUEL
			{
				id: "propulsionEnginesHfo",
				label: "Propulsion HFO",
				type: "text",
				required: false,
				group: "Engine & Fuel",
			},
			{
				id: "propulsionEnginesMgo",
				label: "Propulsion MGO",
				type: "text",
				required: false,
				group: "Engine & Fuel",
			},
			{
				id: "generatorEnginesHfo",
				label: "Generator HFO",
				type: "text",
				required: false,
				group: "Engine & Fuel",
			},
			{
				id: "totalHFO",
				label: "Total HFO",
				type: "text",
				required: false,
				group: "Engine & Fuel",
			},
			{
				id: "totalMGO",
				label: "Total MGO",
				type: "text",
				required: false,
				group: "Engine & Fuel",
			},
			
			// CARGO
			{
				id: "passengers",
				label: "Passengers",
				type: "text",
				required: false,
				group: "Cargo",
			},
			{
				id: "cargoMassMetircTones",
				label: "Cargo Mass MT",
				type: "text",
				required: false,
				group: "Cargo",
			},
			
			// REPORTING
			{
				id: "reportedByPosition",
				label: "Reported By Position",
				type: "text",
				required: false,
				group: "Reporting",
			},
			{
				id: "reportedByUser",
				label: "Reported By User",
				type: "select",
				required: false,
				group: "Reporting",
				filterable: true,
				options: [
					{ value: "bb1a8097", label: "Jarle Auby", color: "#6366F1" },
					{
						value: "c35ed75a",
						label: "Anders Bjørkestøl Olsen",
						color: "#8B5CF6",
					},
					{
						value: "85be9db9",
						label: "Kaptein Color Hybrid",
						color: "#EC4899",
					},
				],
			},
			{
				id: "status",
				label: "Status",
				type: "select",
				required: false,
				group: "Reporting",
				showInCard: true,
				filterable: true,
				options: [
					{ value: "notSubmitted", label: "Not Submitted", color: "#EF4444" },
					{ value: "submitted", label: "Submitted", color: "#10B981" },
					{ value: "resubmit", label: "Resubmit", color: "#8B5CF6" },
				],
			},
		],
	},
	
	{
		id: "employees",
		name: "Employee Directory",
		icon: "Users",
		fields: [
			{
				id: "name",
				label: "Full Name",
				type: "text",
				required: true,
				group: "Personal",
			},
			{
				id: "email",
				label: "Email",
				type: "text",
				required: true,
				group: "Personal",
			},
			{
				id: "department",
				label: "Department",
				type: "select",
				required: true,
				group: "Work",
				showInCard: true,
				filterable: true,
				options: [
					{ value: "engineering", label: "Engineering", color: "#3B82F6" },
					{ value: "operations", label: "Operations", color: "#8FB63E" },
					{ value: "sales", label: "Sales", color: "#10B981" },
				],
			},
			{
				id: "hireDate",
				label: "Hire Date",
				type: "date",
				required: false,
				group: "Work",
			},
		],
	},
	
	{
		id: "dental",
		name: "Dental Health Care",
		icon: "Activity",
		fields: [
			{
				id: "patientName",
				label: "Patient Name",
				type: "text",
				required: true,
				group: "Patient",
			},
			{
				id: "patientId",
				label: "Patient ID",
				type: "text",
				required: true,
				group: "Patient",
			},
			{
				id: "dentist",
				label: "Dentist",
				type: "select",
				required: true,
				group: "Patient",
				filterable: true,
				options: [
					{ value: "dr-smith", label: "Dr. Smith", color: "#6366F1" },
					{ value: "dr-jones", label: "Dr. Jones", color: "#8B5CF6" },
					{ value: "dr-nielsen", label: "Dr. Nielsen", color: "#EC4899" },
				],
			},
			{
				id: "treatment",
				label: "Treatment",
				type: "select",
				required: true,
				group: "Treatment",
				showInCard: true,
				filterable: true,
				options: [
					{ value: "cleaning", label: "Cleaning", color: "#10B981" },
					{ value: "filling", label: "Filling", color: "#F59E0B" },
					{ value: "extraction", label: "Extraction", color: "#EF4444" },
					{ value: "rootCanal", label: "Root Canal", color: "#8B5CF6" },
					{ value: "checkup", label: "Check-up", color: "#3B82F6" },
				],
			},
			{
				id: "appointmentDate",
				label: "Appointment Date",
				type: "date",
				required: true,
				group: "Treatment",
			},
			{
				id: "status",
				label: "Status",
				type: "select",
				required: true,
				group: "Treatment",
				showInCard: true,
				filterable: true,
				options: [
					{ value: "scheduled", label: "Scheduled", color: "#3B82F6" },
					{ value: "completed", label: "Completed", color: "#10B981" },
					{ value: "cancelled", label: "Cancelled", color: "#EF4444" },
					{ value: "noShow", label: "No Show", color: "#F59E0B" },
				],
			},
			{
				id: "notes",
				label: "Notes",
				type: "text",
				required: false,
				group: "Treatment",
			},
			{
				id: "followUp",
				label: "Follow Up",
				type: "date",
				required: false,
				group: "Treatment",
			},
			{
				id: "cost",
				label: "Cost (NOK)",
				type: "text",
				required: false,
				group: "Billing",
			},
			{
				id: "insurance",
				label: "Insurance",
				type: "select",
				required: false,
				group: "Billing",
				filterable: true,
				options: [
					{ value: "covered", label: "Covered", color: "#10B981" },
					{ value: "partial", label: "Partial", color: "#F59E0B" },
					{ value: "notCovered", label: "Not Covered", color: "#EF4444" },
				],
			},
		],
	},
];

export const sampleData: Record<string, Item[]> = {
	voyages: [
		{
			id: "1",
			title: "Color Magic - Report #1001",
			eventKey: "EVT-1001",
			event: "departure",
			eventTime: "2026-02-11T09:00",
			voyageNumber: "VOY-1001",
			fromPort: "Hirtshals",
			toPort: "Larvik",
			latitude: "57.9",
			longitude: "8.7",
			windspeed: "12",
			sailedDistance: "110",
			propulsionEnginesHfo: "2.4",
			propulsionEnginesMgo: "0.8",
			generatorEnginesHfo: "1.2",
			reportedByPosition: "Captain",
			reportedByUser: "bb1a8097",
			status: "submitted",
			passengers: "312",
			cargoMassMetircTones: "850",
			totalHFO: "3.6",
			totalMGO: "0.8",
		},
		{
			id: "2",
			title: "Color Hybrid - Report #1002",
			eventKey: "EVT-1002",
			event: "bunkering",
			eventTime: "2026-02-12T10:00",
			voyageNumber: "VOY-1002",
			fromPort: "Hirtshals",
			toPort: "Kiel",
			latitude: "56.1",
			longitude: "10.2",
			windspeed: "8",
			sailedDistance: "220",
			propulsionEnginesHfo: "3.1",
			propulsionEnginesMgo: "1.2",
			generatorEnginesHfo: "1.5",
			reportedByPosition: "First Officer",
			reportedByUser: "c35ed75a",
			status: "notSubmitted",
			passengers: "280",
			cargoMassMetircTones: "920",
			totalHFO: "4.6",
			totalMGO: "1.2",
		},
		{
			id: "3",
			title: "SuperSpeed 1 - Report #1003",
			eventKey: "EVT-1003",
			event: "arrival",
			eventTime: "2026-02-13T11:00",
			voyageNumber: "VOY-1003",
			fromPort: "Larvik",
			toPort: "Kristiansand",
			latitude: "58.1",
			longitude: "7.9",
			windspeed: "15",
			sailedDistance: "95",
			propulsionEnginesHfo: "1.8",
			propulsionEnginesMgo: "0.6",
			generatorEnginesHfo: "0.9",
			reportedByPosition: "Captain",
			reportedByUser: "85be9db9",
			status: "resubmit",
			passengers: "195",
			cargoMassMetircTones: "430",
			totalHFO: "2.7",
			totalMGO: "0.6",
		},
		{
			id: "4",
			title: "SuperSpeed 2 - Report #1004",
			eventKey: "EVT-1004",
			event: "departure",
			eventTime: "2026-02-14T12:00",
			voyageNumber: "VOY-1004",
			fromPort: "Kristiansand",
			toPort: "Larvik",
			latitude: "58.1",
			longitude: "8.0",
			windspeed: "10",
			sailedDistance: "95",
			propulsionEnginesHfo: "1.9",
			propulsionEnginesMgo: "0.7",
			generatorEnginesHfo: "1.0",
			reportedByPosition: "Captain",
			reportedByUser: "bb1a8097",
			status: "submitted",
			passengers: "210",
			cargoMassMetircTones: "510",
			totalHFO: "2.9",
			totalMGO: "0.7",
		},
		{
			id: "5",
			title: "Color Fantasy - Report #1005",
			eventKey: "EVT-1005",
			event: "bunkering",
			eventTime: "2026-02-15T13:00",
			voyageNumber: "VOY-1005",
			fromPort: "Sandefjord",
			toPort: "Stromstad",
			latitude: "59.1",
			longitude: "10.5",
			windspeed: "6",
			sailedDistance: "75",
			propulsionEnginesHfo: "1.5",
			propulsionEnginesMgo: "0.5",
			generatorEnginesHfo: "0.8",
			reportedByPosition: "Chief Officer",
			reportedByUser: "c35ed75a",
			status: "submitted",
			passengers: "420",
			cargoMassMetircTones: "1100",
			totalHFO: "2.3",
			totalMGO: "0.5",
		},
		{
			id: "6",
			title: "Color Magic - Report #1006",
			eventKey: "EVT-1006",
			event: "arrival",
			eventTime: "2026-02-16T14:00",
			voyageNumber: "VOY-1006",
			fromPort: "Stromstad",
			toPort: "Sandefjord",
			latitude: "59.0",
			longitude: "10.4",
			windspeed: "9",
			sailedDistance: "75",
			propulsionEnginesHfo: "1.6",
			propulsionEnginesMgo: "0.5",
			generatorEnginesHfo: "0.8",
			reportedByPosition: "Captain",
			reportedByUser: "bb1a8097",
			status: "notSubmitted",
			passengers: "398",
			cargoMassMetircTones: "980",
			totalHFO: "2.4",
			totalMGO: "0.5",
		},
		{
			id: "7",
			title: "Color Hybrid - Report #1007",
			eventKey: "EVT-1007",
			event: "departure",
			eventTime: "2026-02-17T15:00",
			voyageNumber: "VOY-1007",
			fromPort: "Kiel",
			toPort: "Oslo",
			latitude: "55.7",
			longitude: "10.9",
			windspeed: "18",
			sailedDistance: "480",
			propulsionEnginesHfo: "5.2",
			propulsionEnginesMgo: "1.8",
			generatorEnginesHfo: "2.1",
			reportedByPosition: "Captain",
			reportedByUser: "85be9db9",
			status: "submitted",
			passengers: "560",
			cargoMassMetircTones: "1450",
			totalHFO: "7.3",
			totalMGO: "1.8",
		},
		{
			id: "8",
			title: "SuperSpeed 1 - Report #1008",
			eventKey: "EVT-1008",
			event: "bunkering",
			eventTime: "2026-02-18T16:00",
			voyageNumber: "VOY-1008",
			fromPort: "Oslo",
			toPort: "Kiel",
			latitude: "59.9",
			longitude: "10.7",
			windspeed: "11",
			sailedDistance: "480",
			propulsionEnginesHfo: "5.0",
			propulsionEnginesMgo: "1.7",
			generatorEnginesHfo: "2.0",
			reportedByPosition: "First Officer",
			reportedByUser: "c35ed75a",
			status: "resubmit",
			passengers: "490",
			cargoMassMetircTones: "1380",
			totalHFO: "7.0",
			totalMGO: "1.7",
		},
		{
			id: "9",
			title: "Color Fantasy - Report #1009",
			eventKey: "EVT-1009",
			event: "arrival",
			eventTime: "2026-02-19T08:00",
			voyageNumber: "VOY-1009",
			fromPort: "Oslo",
			toPort: "Copenhagen",
			latitude: "55.6",
			longitude: "12.5",
			windspeed: "14",
			sailedDistance: "320",
			propulsionEnginesHfo: "3.8",
			propulsionEnginesMgo: "1.3",
			generatorEnginesHfo: "1.6",
			reportedByPosition: "Captain",
			reportedByUser: "bb1a8097",
			status: "submitted",
			passengers: "445",
			cargoMassMetircTones: "1200",
			totalHFO: "5.4",
			totalMGO: "1.3",
		},
		{
			id: "10",
			title: "SuperSpeed 2 - Report #1010",
			eventKey: "EVT-1010",
			event: "departure",
			eventTime: "2026-02-20T09:30",
			voyageNumber: "VOY-1010",
			fromPort: "Copenhagen",
			toPort: "Hirtshals",
			latitude: "55.7",
			longitude: "12.6",
			windspeed: "7",
			sailedDistance: "180",
			propulsionEnginesHfo: "2.1",
			propulsionEnginesMgo: "0.9",
			generatorEnginesHfo: "1.1",
			reportedByPosition: "First Officer",
			reportedByUser: "c35ed75a",
			status: "notSubmitted",
			passengers: "310",
			cargoMassMetircTones: "760",
			totalHFO: "3.2",
			totalMGO: "0.9",
		},
		{
			id: "11",
			title: "Color Magic - Report #1011",
			eventKey: "EVT-1011",
			event: "bunkering",
			eventTime: "2026-02-21T11:00",
			voyageNumber: "VOY-1011",
			fromPort: "Hirtshals",
			toPort: "Bergen",
			latitude: "60.3",
			longitude: "5.3",
			windspeed: "20",
			sailedDistance: "540",
			propulsionEnginesHfo: "6.1",
			propulsionEnginesMgo: "2.1",
			generatorEnginesHfo: "2.4",
			reportedByPosition: "Captain",
			reportedByUser: "85be9db9",
			status: "resubmit",
			passengers: "520",
			cargoMassMetircTones: "1600",
			totalHFO: "8.5",
			totalMGO: "2.1",
		},
		{
			id: "12",
			title: "Color Hybrid - Report #1012",
			eventKey: "EVT-1012",
			event: "arrival",
			eventTime: "2026-02-22T14:00",
			voyageNumber: "VOY-1012",
			fromPort: "Bergen",
			toPort: "Stavanger",
			latitude: "58.9",
			longitude: "5.7",
			windspeed: "11",
			sailedDistance: "180",
			propulsionEnginesHfo: "2.2",
			propulsionEnginesMgo: "0.8",
			generatorEnginesHfo: "1.1",
			reportedByPosition: "Captain",
			reportedByUser: "bb1a8097",
			status: "submitted",
			passengers: "380",
			cargoMassMetircTones: "950",
			totalHFO: "3.3",
			totalMGO: "0.8",
		},
		{
			id: "13",
			title: "SuperSpeed 1 - Report #1013",
			eventKey: "EVT-1013",
			event: "departure",
			eventTime: "2026-02-23T10:00",
			voyageNumber: "VOY-1013",
			fromPort: "Stavanger",
			toPort: "Kristiansand",
			latitude: "58.1",
			longitude: "7.9",
			windspeed: "9",
			sailedDistance: "130",
			propulsionEnginesHfo: "1.7",
			propulsionEnginesMgo: "0.6",
			generatorEnginesHfo: "0.9",
			reportedByPosition: "First Officer",
			reportedByUser: "c35ed75a",
			status: "submitted",
			passengers: "225",
			cargoMassMetircTones: "580",
			totalHFO: "2.6",
			totalMGO: "0.6",
		},
		{
			id: "14",
			title: "Color Fantasy - Report #1014",
			eventKey: "EVT-1014",
			event: "bunkering",
			eventTime: "2026-02-24T13:00",
			voyageNumber: "VOY-1014",
			fromPort: "Kristiansand",
			toPort: "Gothenburg",
			latitude: "57.7",
			longitude: "11.9",
			windspeed: "16",
			sailedDistance: "210",
			propulsionEnginesHfo: "2.7",
			propulsionEnginesMgo: "1.0",
			generatorEnginesHfo: "1.3",
			reportedByPosition: "Captain",
			reportedByUser: "85be9db9",
			status: "notSubmitted",
			passengers: "468",
			cargoMassMetircTones: "1250",
			totalHFO: "4.0",
			totalMGO: "1.0",
		},
		{
			id: "15",
			title: "Color Magic - Report #1015",
			eventKey: "EVT-1015",
			event: "arrival",
			eventTime: "2026-02-25T09:00",
			voyageNumber: "VOY-1015",
			fromPort: "Gothenburg",
			toPort: "Oslo",
			latitude: "59.9",
			longitude: "10.7",
			windspeed: "5",
			sailedDistance: "290",
			propulsionEnginesHfo: "3.4",
			propulsionEnginesMgo: "1.2",
			generatorEnginesHfo: "1.5",
			reportedByPosition: "Captain",
			reportedByUser: "bb1a8097",
			status: "submitted",
			passengers: "502",
			cargoMassMetircTones: "1320",
			totalHFO: "4.9",
			totalMGO: "1.2",
		},
		{
			id: "16",
			title: "SuperSpeed 2 - Report #1016",
			eventKey: "EVT-1016",
			event: "departure",
			eventTime: "2026-02-26T11:30",
			voyageNumber: "VOY-1016",
			fromPort: "Oslo",
			toPort: "Larvik",
			latitude: "59.1",
			longitude: "10.0",
			windspeed: "13",
			sailedDistance: "100",
			propulsionEnginesHfo: "1.4",
			propulsionEnginesMgo: "0.5",
			generatorEnginesHfo: "0.7",
			reportedByPosition: "First Officer",
			reportedByUser: "c35ed75a",
			status: "resubmit",
			passengers: "178",
			cargoMassMetircTones: "420",
			totalHFO: "2.1",
			totalMGO: "0.5",
		},
		{
			id: "17",
			title: "Color Hybrid - Report #1017",
			eventKey: "EVT-1017",
			event: "arrival",
			eventTime: "2026-02-27T08:30",
			voyageNumber: "VOY-1017",
			fromPort: "Larvik",
			toPort: "Hirtshals",
			latitude: "57.6",
			longitude: "9.9",
			windspeed: "8",
			sailedDistance: "110",
			propulsionEnginesHfo: "1.5",
			propulsionEnginesMgo: "0.5",
			generatorEnginesHfo: "0.8",
			reportedByPosition: "Captain",
			reportedByUser: "bb1a8097",
			status: "submitted",
			passengers: "290",
			cargoMassMetircTones: "700",
			totalHFO: "2.3",
			totalMGO: "0.5",
		},
		{
			id: "18",
			title: "SuperSpeed 1 - Report #1018",
			eventKey: "EVT-1018",
			event: "bunkering",
			eventTime: "2026-02-28T10:00",
			voyageNumber: "VOY-1018",
			fromPort: "Hirtshals",
			toPort: "Sandefjord",
			latitude: "59.1",
			longitude: "10.2",
			windspeed: "12",
			sailedDistance: "130",
			propulsionEnginesHfo: "1.8",
			propulsionEnginesMgo: "0.7",
			generatorEnginesHfo: "0.9",
			reportedByPosition: "First Officer",
			reportedByUser: "c35ed75a",
			status: "notSubmitted",
			passengers: "340",
			cargoMassMetircTones: "820",
			totalHFO: "2.7",
			totalMGO: "0.7",
		},
		{
			id: "19",
			title: "Color Fantasy - Report #1019",
			eventKey: "EVT-1019",
			event: "departure",
			eventTime: "2026-03-01T09:00",
			voyageNumber: "VOY-1019",
			fromPort: "Sandefjord",
			toPort: "Kiel",
			latitude: "54.3",
			longitude: "10.1",
			windspeed: "17",
			sailedDistance: "560",
			propulsionEnginesHfo: "6.4",
			propulsionEnginesMgo: "2.2",
			generatorEnginesHfo: "2.5",
			reportedByPosition: "Captain",
			reportedByUser: "85be9db9",
			status: "submitted",
			passengers: "610",
			cargoMassMetircTones: "1700",
			totalHFO: "8.9",
			totalMGO: "2.2",
		},
		{
			id: "20",
			title: "Color Magic - Report #1020",
			eventKey: "EVT-1020",
			event: "arrival",
			eventTime: "2026-03-02T12:00",
			voyageNumber: "VOY-1020",
			fromPort: "Kiel",
			toPort: "Copenhagen",
			latitude: "55.6",
			longitude: "12.5",
			windspeed: "10",
			sailedDistance: "95",
			propulsionEnginesHfo: "1.3",
			propulsionEnginesMgo: "0.5",
			generatorEnginesHfo: "0.7",
			reportedByPosition: "Captain",
			reportedByUser: "bb1a8097",
			status: "resubmit",
			passengers: "415",
			cargoMassMetircTones: "1050",
			totalHFO: "2.0",
			totalMGO: "0.5",
		},
		{
			id: "21",
			title: "Color Hybrid - Report #1021",
			eventKey: "EVT-1021",
			event: "bunkering",
			eventTime: "2026-03-03T14:00",
			voyageNumber: "VOY-1021",
			fromPort: "Copenhagen",
			toPort: "Oslo",
			latitude: "59.9",
			longitude: "10.7",
			windspeed: "6",
			sailedDistance: "490",
			propulsionEnginesHfo: "5.5",
			propulsionEnginesMgo: "1.9",
			generatorEnginesHfo: "2.2",
			reportedByPosition: "First Officer",
			reportedByUser: "c35ed75a",
			status: "submitted",
			passengers: "535",
			cargoMassMetircTones: "1400",
			totalHFO: "7.7",
			totalMGO: "1.9",
		},
		{
			id: "22",
			title: "SuperSpeed 2 - Report #1022",
			eventKey: "EVT-1022",
			event: "departure",
			eventTime: "2026-03-04T08:00",
			voyageNumber: "VOY-1022",
			fromPort: "Oslo",
			toPort: "Stromstad",
			latitude: "59.0",
			longitude: "11.2",
			windspeed: "9",
			sailedDistance: "80",
			propulsionEnginesHfo: "1.2",
			propulsionEnginesMgo: "0.4",
			generatorEnginesHfo: "0.6",
			reportedByPosition: "Captain",
			reportedByUser: "85be9db9",
			status: "notSubmitted",
			passengers: "195",
			cargoMassMetircTones: "480",
			totalHFO: "1.8",
			totalMGO: "0.4",
		},
		{
			id: "23",
			title: "Color Fantasy - Report #1023",
			eventKey: "EVT-1023",
			event: "arrival",
			eventTime: "2026-03-05T11:00",
			voyageNumber: "VOY-1023",
			fromPort: "Stromstad",
			toPort: "Kristiansand",
			latitude: "58.1",
			longitude: "7.9",
			windspeed: "14",
			sailedDistance: "160",
			propulsionEnginesHfo: "2.0",
			propulsionEnginesMgo: "0.7",
			generatorEnginesHfo: "1.0",
			reportedByPosition: "Captain",
			reportedByUser: "bb1a8097",
			status: "submitted",
			passengers: "350",
			cargoMassMetircTones: "890",
			totalHFO: "3.0",
			totalMGO: "0.7",
		},
		{
			id: "24",
			title: "SuperSpeed 1 - Report #1024",
			eventKey: "EVT-1024",
			event: "bunkering",
			eventTime: "2026-03-06T13:00",
			voyageNumber: "VOY-1024",
			fromPort: "Kristiansand",
			toPort: "Stavanger",
			latitude: "58.9",
			longitude: "5.7",
			windspeed: "11",
			sailedDistance: "145",
			propulsionEnginesHfo: "1.9",
			propulsionEnginesMgo: "0.7",
			generatorEnginesHfo: "1.0",
			reportedByPosition: "First Officer",
			reportedByUser: "c35ed75a",
			status: "resubmit",
			passengers: "265",
			cargoMassMetircTones: "640",
			totalHFO: "2.9",
			totalMGO: "0.7",
		},
	],
	
	employees: [
		{
			id: "1",
			name: "John Smith",
			email: "john.smith@maranics.com",
			department: "engineering",
			hireDate: "2024-01-15",
		},
		{
			id: "2",
			name: "Sarah Connor",
			email: "sarah.connor@maranics.com",
			department: "operations",
			hireDate: "2023-06-20",
		},
		{
			id: "3",
			name: "Mike Johnson",
			email: "mike.johnson@maranics.com",
			department: "sales",
			hireDate: "2025-03-10",
		},
		{
			id: "4",
			name: "Anna Berg",
			email: "anna.berg@maranics.com",
			department: "engineering",
			hireDate: "2022-09-01",
		},
		{
			id: "5",
			name: "Lars Eriksen",
			email: "lars.eriksen@maranics.com",
			department: "operations",
			hireDate: "2023-11-15",
		},
		{
			id: "6",
			name: "Emma Nielsen",
			email: "emma.nielsen@maranics.com",
			department: "sales",
			hireDate: "2024-05-22",
		},
	],
	
	dental: [
		{
			id: "1",
			patientName: "Alice Freeman",
			patientId: "P-1001",
			dentist: "dr-smith",
			treatment: "cleaning",
			appointmentDate: "2026-03-10T09:00",
			status: "scheduled",
			notes: "Regular checkup",
			followUp: "2026-09-10T09:00",
			cost: "850",
			insurance: "covered",
		},
		{
			id: "2",
			patientName: "Bob Thompson",
			patientId: "P-1002",
			dentist: "dr-jones",
			treatment: "filling",
			appointmentDate: "2026-03-11T10:00",
			status: "completed",
			notes: "Cavity on molar",
			followUp: "2026-06-11T10:00",
			cost: "1200",
			insurance: "partial",
		},
		{
			id: "3",
			patientName: "Sara Nielsen",
			patientId: "P-1003",
			dentist: "dr-nielsen",
			treatment: "extraction",
			appointmentDate: "2026-03-12T11:00",
			status: "cancelled",
			notes: "Patient rescheduled",
			followUp: "",
			cost: "1500",
			insurance: "notCovered",
		},
		{
			id: "4",
			patientName: "Erik Hansen",
			patientId: "P-1004",
			dentist: "dr-smith",
			treatment: "rootCanal",
			appointmentDate: "2026-03-13T14:00",
			status: "scheduled",
			notes: "Severe pain reported",
			followUp: "2026-04-13T14:00",
			cost: "4500",
			insurance: "partial",
		},
		{
			id: "5",
			patientName: "Maria Olsen",
			patientId: "P-1005",
			dentist: "dr-jones",
			treatment: "checkup",
			appointmentDate: "2026-03-14T09:00",
			status: "completed",
			notes: "All good",
			followUp: "2026-09-14T09:00",
			cost: "650",
			insurance: "covered",
		},
		{
			id: "6",
			patientName: "Lars Berg",
			patientId: "P-1006",
			dentist: "dr-nielsen",
			treatment: "cleaning",
			appointmentDate: "2026-03-15T11:00",
			status: "noShow",
			notes: "Did not attend",
			followUp: "2026-03-22T11:00",
			cost: "850",
			insurance: "covered",
		},
	],
};
